### ISSUE TITLE
Add Github Pages

### ISSUE THREAD

**Issue by scyilk** [ramazancetinkaya/snake-game#2]
Most people, me included, can't be bothered to clone the game down to their machine just to take a quick peek and play a round or two. It seems you're quite new to Github, considering you didn't name your commits, I can help you through the process of using Github Pages or you can [let me google that for you](https://letmegooglethat.com/?q=github+pages). (/s)

**Comment by ramazancetinkaya** [comment]
I am aware that I haven't published the game online on GitHub, and this is due to realizing that I haven't developed the game sufficiently. I will soon release a new version of the game, and along with that, I will publish the game online on GitHub. Thank you for your interest and attention to the project. Wishing you a great day.

**Comment by ramazancetinkaya** [comment]
@erenerturk1 Additionally, it is my fault not to mention in the README page that the game is still in development. I will also update the README page with the release of the new version of the game.
